### ISSUE TITLE
Pin connections please

### ISSUE THREAD

**Issue by puneethsb** [JobNoorman/PmodClsArduino#1]
Can someone please share pin connections of PmodCls with arduino 

also I'm facing the error 

avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0xd1

I'm not understanding what it is

**Comment by mtvec** [comment]
It depends on how you want to talk with the PmodCLS module. As described in the [README](https://github.com/JobNoorman/PmodClsArduino/blob/master/README.md), the `PmodCls` class simply takes a function pointer as input and calls this function with the bytes to write to the PmodCLS. You have to make sure those bytes are sent to the PmodCLS.

Please have a look at the [HelloWorld](https://github.com/JobNoorman/PmodClsArduino/blob/master/examples/HelloWorld/HelloWorld.ino) to see how you can use UART to talk to the PmodCLS. In this case, the PmodCLS should be wired to the Arduino's UART and configured to take input from its UART (see the PmodCLS documentation on how to do that).

As for the avrdude errors, I'm afraid this is not the right place to ask these questions.
